apiVersion: v1
kind: Service
metadata:
  name: service-courses
spec:
  selector:
    app: service-courses
  type: NodePort
  ports:
    - name: http
      port: 8081
      nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-courses
spec:
  selector:
    matchLabels:
      app: service-courses
  replicas: 1
  template:
    metadata:
      labels:
        app: service-courses
    spec:
      containers:
        - name: server
          image: alinastep123/service-courses
          ports:
            - name: http
              containerPort: 8081